repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        name: "Enforce LF newlines on most files"
        args:
          - "--fix=lf"
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-docstring-first
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        name: black-ipynb
        additional_dependencies: [jupyter]
        files: ^notebooks/.*\.ipynb$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix, --preview]
      - id: ruff-format

  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-fmt
        name: deno-fmt-md
        files: ^docs/.*\.md$
