[project]
name = "khive"
version = "0.1.6"
description = "khive mono-repo tooling"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiocache>=0.12.3",
    "aiohttp>=3.11.18",
    "aiolimiter>=1.2.1",
    "backoff>=2.2.1",
    "datamodel-code-generator[http]>=0.30.1",
    # Pin openai until v2 beta stabilizes
    "openai>=1.76.2,<2",
    "prance>=25.4.8.0",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.9.1",
]

[dependency-groups]
dev = [
    "black[jupyter]>=25.1.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "isort>=6.0.1",
    "networkx>=3.4",
    "matplotlib>=3.8.0",
    "pytest-asyncio>=0.26.0",
    "pytest>=8.3.5",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["khive"]
include-package-data = true

[tool.hatch.build]
exclude = [
    "dev/*",
    "data/*",
    "notebooks/*",
    "tests/*",
    "*.pyc",
    "__pycache__",
    "temp_logs/*",
    "logs/*",
    "verification",
    "scripts",
]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests that require external dependencies or network access",
    "unit: marks fast unit tests"
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[project.scripts]                # PEP 621 console-scripts table
khive         = "khive.khive_cli:main"
